name: Tests

on: [push, pull_request]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./test.sh
  test_windows:
    name: Windows build and tests
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install dependencies
        run: |
          Invoke-WebRequest -URI https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip -OutFile libsodium-1.0.18-stable-msvc.zip
          tar -xf libsodium-1.0.18-stable-msvc.zip
          rm libsodium-1.0.18-stable-msvc.zip
        shell: pwsh

      - name: Run msbuild
        working-directory: ./build
        run: |
          msbuild pgsodium.vcxproj /p:libsodiumLocation=..\libsodium /p:PostgreSQLLocation=%PGROOT% /p:Configuration=Release /p:Platform=x64 /p:platformToolset=v143

      - name: Install libraries
        run: |
          cp .\libsodium\x64\Release\v143\dynamic\libsodium.dll %PGROOT%\lib
          cp .\build\x64\Release\pgsodium.dll %PGROOT%\lib
          cp pgsodium.control %PGROOT%\share\extension
          cp .\sql\* %PGROOT%\share\extension
          cp .\getkey_scripts\pgsodium_getkey.bat %PGROOT%\data
          pg_ctl -D %PGROOT%\data
